# Generated by Django 5.1.1 on 2024-09-07 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortlink',
            old_name='accessed',
            new_name='accessCount',
        ),
        migrations.RenameField(
            model_name='shortlink',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='shortlink',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='shortlink',
            old_name='original_link',
            new_name='url',
        ),
    ]
